// react-password-validation/src/app.tsx
import { useState } from 'react';
import { CreateUserForm } from './create-user-form';

function App() {
  const [userWasCreated, setUserWasCreated] = useState(false);
  if (userWasCreated) {
    return <p>User was successfully created!</p>;
  }

  return <CreateUserForm setUserWasCreated={setUserWasCreated} />;
}

export default App;

// vue-password-validation/src/app.vue
<script setup lang="ts">
import { ref } from 'vue';
import CreateUserForm from './create-user-form.vue';

const userWasCreated = ref(false);
</script>

<template>
  <CreateUserForm
    v-if="!userWasCreated"
    @create-successful="userWasCreated = true"
  />

  <p v-else>User was successfully created!</p>
</template>
