// react-password-validation/src/create-user-form.tsx
import {
  type CSSProperties,
  type Dispatch,
  type SetStateAction,
  useState,
} from 'react';

const BEARER_TOKEN = '';
const URL =
  'https://api.challenge.hennge.com/password-validation-challenge-api/001';
const PATH = '/challenge-signup';

const ERROR_MESSAGES = {
  validationMsg: {
    passwordTooShort: 'Password must be at least 10 characters long',
    passwordTooLong: 'Password must be at most 24 characters long',
    passwordNoSpaces: 'Password cannot contain spaces',
    passwordNeedsNumber: 'Password must contain at least one number',
    passwordNeedsUpper: 'Password must contain at least one uppercase letter',
    passwordNeedsLower: 'Password must contain at least one lowercase letter',
  },
  apiMsg: {
    unauthorized: 'Not authenticated to access this resource.',
    notAllowed:
      'Sorry, the entered password is not allowed, please try a different one.',
    server: 'Something went wrong, please try again.',
  },
};
enum ErrorCode {
  InvalidRequest = 'invalid_request',
  TooShort = 'too_short',
  TooLong = 'too_long',
  NoWhitespace = 'no_whitespace',
  MissingDigits = 'missing_digits',
  MissingUppercase = 'missing_uppercase',
  MissingLowercase = 'missing_lowercase',
  NotAllowed = 'not_allowed',
}

const messageMap: Record<ErrorCode, string> = {
  [ErrorCode.InvalidRequest]: '',
  [ErrorCode.TooShort]: ERROR_MESSAGES.validationMsg.passwordTooShort,
  [ErrorCode.TooLong]: ERROR_MESSAGES.validationMsg.passwordTooLong,
  [ErrorCode.NoWhitespace]: ERROR_MESSAGES.validationMsg.passwordNoSpaces,
  [ErrorCode.MissingDigits]: ERROR_MESSAGES.validationMsg.passwordNeedsNumber,
  [ErrorCode.MissingUppercase]: ERROR_MESSAGES.validationMsg.passwordNeedsUpper,
  [ErrorCode.MissingLowercase]: ERROR_MESSAGES.validationMsg.passwordNeedsLower,
  [ErrorCode.NotAllowed]: ERROR_MESSAGES.apiMsg.notAllowed,
};

interface SignupRequest {
  username: string;
  password: string;
}

interface ApiResponseSuccess {
  success: boolean;
}

interface ApiResponseFailure extends ApiResponseSuccess {
  errors: ErrorCode[];
}

const signup = async (request: SignupRequest) => {
  return await fetch(`${URL}${PATH}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${BEARER_TOKEN}`,
    },
    body: JSON.stringify(request),
  });
};

const validatePassword = (password: string) => {
  const validationErrors = [];

  if (password.length < 10) {
    validationErrors.push(ERROR_MESSAGES.validationMsg.passwordTooShort);
  }
  if (password.length > 24) {
    validationErrors.push(ERROR_MESSAGES.validationMsg.passwordTooLong);
  }
  if (/\s/.test(password)) {
    validationErrors.push(ERROR_MESSAGES.validationMsg.passwordNoSpaces);
  }
  if (!/\d/.test(password)) {
    validationErrors.push(ERROR_MESSAGES.validationMsg.passwordNeedsNumber);
  }
  if (!/[A-Z]/.test(password)) {
    validationErrors.push(ERROR_MESSAGES.validationMsg.passwordNeedsUpper);
  }
  if (!/[a-z]/.test(password)) {
    validationErrors.push(ERROR_MESSAGES.validationMsg.passwordNeedsLower);
  }

  return validationErrors;
};

const getValidationMessages = (errors: ErrorCode[]): string[] => {
  if (!errors || errors.length === 0) {
    return [];
  }

  return errors.map((errorCode) => messageMap[errorCode]);
};

interface CreateUserFormProps {
  setUserWasCreated: Dispatch<SetStateAction<boolean>>;
}

function CreateUserForm({ setUserWasCreated }: CreateUserFormProps) {
  const [username, setUsername] = useState<string>('');
  const [password, setPassword] = useState<string>('');
  const [passwordValidationErrors, setPasswordValidationErrors] = useState<
    string[]
  >([]);
  const [apiErrors, setApiErrors] = useState<string[]>([]);

  const handleUsernameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setUsername(event.target.value);
  };

  const handlePasswordChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setPassword(event.target.value);
  };

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    setPasswordValidationErrors([]);
    setApiErrors([]);

    const validationErrors = validatePassword(password);

    setPasswordValidationErrors(validationErrors);

    if (validationErrors.length === 0) {
      try {
        const res = await signup({ username, password });
        if (res.ok) {
          setUserWasCreated(true);
        } else {
          if (res.status === 401 || res.status === 403) {
            setApiErrors([ERROR_MESSAGES.apiMsg.unauthorized]);
          } else if (res.status === 422) {
            const response: ApiResponseFailure = await res.json();
            const apiErrors = getValidationMessages(response.errors);
            setApiErrors(apiErrors);
          } else if (res.status === 500) {
            setApiErrors([ERROR_MESSAGES.apiMsg.server]);
          }
        }
      } catch (error) {
        setApiErrors([ERROR_MESSAGES.apiMsg.server]);
      }
    }
  };

  return (
    <div style={formWrapper}>
      {apiErrors.length > 0 && (
        <div style={apiErrorContainer}>
          <h3>Api Errors:</h3>
          <ul style={apiErrorMessage}>
            {apiErrors.map((error) => (
              <li key={error}>{error}</li>
            ))}
          </ul>
        </div>
      )}
      <form style={form} onSubmit={handleSubmit}>
        {/* make sure the username and password are submitted */}
        {/* make sure the inputs have the accessible names of their labels */}
        <label htmlFor="username" style={formLabel}>
          Username
        </label>
        <input
          id="username"
          autoComplete="username"
          type="text"
          aria-invalid={!username}
          style={formInput}
          value={username}
          onChange={handleUsernameChange}
          required
        />

        <label htmlFor="password" style={formLabel}>
          Password
        </label>
        <input
          id="password"
          // type="password"
          aria-invalid={passwordValidationErrors.length > 0}
          style={{
            ...formInput,
            ...(passwordValidationErrors.length > 0 ? invalidInput : {}),
          }}
          value={password}
          onChange={handlePasswordChange}
          required
        />

        {passwordValidationErrors.length > 0 && (
          <ul style={validationErrorMessage}>
            {passwordValidationErrors.map((error) => (
              <li key={error}>{error}</li>
            ))}
          </ul>
        )}

        <button type="submit" style={formButton}>
          Create User
        </button>
      </form>
    </div>
  );
}

export { CreateUserForm };

const formWrapper: CSSProperties = {
  maxWidth: '500px',
  width: '80%',
  backgroundColor: '#efeef5',
  padding: '24px',
  borderRadius: '8px',
};

const form: CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  gap: '8px',
};

const formLabel: CSSProperties = {
  fontWeight: 700,
};

const formInput: CSSProperties = {
  outline: 'none',
  padding: '8px 16px',
  height: '40px',
  fontSize: '14px',
  backgroundColor: '#f8f7fa',
  border: '1px solid rgba(0, 0, 0, 0.12)',
  borderRadius: '4px',
};

const formButton: CSSProperties = {
  outline: 'none',
  borderRadius: '4px',
  border: '1px solid rgba(0, 0, 0, 0.12)',
  backgroundColor: '#7135d2',
  color: 'white',
  fontSize: '16px',
  fontWeight: 500,
  height: '40px',
  padding: '0 8px',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  marginTop: '8px',
  alignSelf: 'flex-end',
  cursor: 'pointer',
};

const validationErrorMessage: CSSProperties = {
  color: 'red',
  padding: '2px 16px',
};

const apiErrorContainer: CSSProperties = {
  border: '2px solid red',
  color: 'red',
  padding: '0px 8px',
};

const apiErrorMessage: CSSProperties = {
  padding: '8px 26px',
  fontWeight: 700,
};

const invalidInput: CSSProperties = {
  borderColor: 'red',
  boxShadow: '0 0 0 1px red',
};

// vue-password-validation/src/create-user-form.vue
<script setup lang="ts">
import { ref } from 'vue';

const emit = defineEmits(['create-successful']);

const username = ref('');
const password = ref('');
const showPassword = ref(false);
const isLoading = ref(false);
const errors = ref<{ username?: string; password?: string[]; api?: string }>(
  {},
);

enum ErrorType {
  NOT_ALLOWED = 'not_allowed',
}
const ERROR_MESSAGES = {
  passwordTooShort: 'Password must be at least 10 characters long',
  passwordTooLong: 'Password must be at most 24 characters long',
  passwordNoSpaces: 'Password cannot contain spaces',
  passwordNeedsNumber: 'Password must contain at least one number',
  passwordNeedsUpper: 'Password must contain at least one uppercase letter',
  passwordNeedsLower: 'Password must contain at least one lowercase letter',
  apiUnauthorized: 'Not authenticated to access this resource.',
  apiNotAllowed:
    'Sorry, the entered password is not allowed, please try a different one.',
  apiServer: 'Something went wrong, please try again.',
};
const API_TOKEN = '';

function validatePassword(pw: string): string[] {
  const messages: string[] = [];

  if (pw.length < 10) messages.push(ERROR_MESSAGES.passwordTooShort);
  if (pw.length > 24) messages.push(ERROR_MESSAGES.passwordTooLong);
  if (/\s/.test(pw)) messages.push(ERROR_MESSAGES.passwordNoSpaces);
  if (!/\d/.test(pw)) messages.push(ERROR_MESSAGES.passwordNeedsNumber);
  if (!/[a-z]/.test(pw)) messages.push(ERROR_MESSAGES.passwordNeedsLower);
  if (!/[A-Z]/.test(pw)) messages.push(ERROR_MESSAGES.passwordNeedsUpper);

  return messages;
}

async function apiRequest<T>(
  route: string,
  method: 'GET' | 'POST' | 'PUT' | 'DELETE',
  body?: unknown,
): Promise<{ success: boolean; data?: T; error?: string }> {
  try {
    const res = await fetch(
      `https://api.challenge.hennge.com/password-validation-challenge-api/001${route}`,
      {
        method,
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${API_TOKEN}`,
        },
        body: body ? JSON.stringify(body) : undefined,
      },
    );

    if (res.ok) {
      return { success: true };
    } else if (res.status === 401 || res.status === 403) {
      return { success: false, error: ERROR_MESSAGES.apiUnauthorized };
    } else if (res.status === 422) {
      const data = await res.json();
      if (data.errors && data.errors.includes(ErrorType.NOT_ALLOWED)) {
        return { success: false, error: ERROR_MESSAGES.apiNotAllowed };
      }
    } else if (res.status === 500) {
      return { success: false, error: ERROR_MESSAGES.apiServer };
    }
    return { success: false, error: ERROR_MESSAGES.apiServer };
  } catch (err) {
    return { success: false, error: ERROR_MESSAGES.apiServer };
  }
}

async function handleSubmit(e: Event) {
  e.preventDefault();
  errors.value = {};

  const pwErrors = validatePassword(password.value);
  if (pwErrors.length > 0) {
    errors.value.password = pwErrors;
    return;
  }

  isLoading.value = true;
  const result = await apiRequest('/challenge-signup', 'POST', {
    username: username.value,
    password: password.value,
  });

  if (result.success) {
    emit('create-successful');
    username.value = '';
    password.value = '';
  } else {
    errors.value.api = result.error;
  }
  isLoading.value = false;
}
</script>

<template>
  <div class="form-wrapper">
    <div v-if="errors.api" class="api-error" role="alert">
      {{ errors.api }}
    </div>

    <form class="form" @submit="handleSubmit">
      <label for="username">Username</label>
      <input
        id="username"
        required
        v-model="username"
        type="text"
        :disabled="isLoading"
        @input="errors.username = undefined"
        :aria-invalid="!!errors.username"
        aria-describedby="username-error"
      />
      <p v-if="errors.username" id="username-error" role="alert" class="error">
        {{ errors.username }}
      </p>

      <label for="password">Password</label>
      <div class="password-wrapper">
        <input
          id="password"
          required
          v-model="password"
          :type="showPassword ? 'text' : 'password'"
          :disabled="isLoading"
          @input="errors.password = undefined"
          :aria-invalid="!!errors.password"
          aria-describedby="password-error"
        />
        <button
          type="button"
          class="toggle-button"
          :disabled="isLoading"
          @click="showPassword = !showPassword"
          :aria-label="showPassword ? 'Hide password' : 'Show password'"
        >
          {{ showPassword ? 'Hide' : 'Show' }}
        </button>
      </div>
      <ul
        v-if="errors.password"
        id="password-error"
        role="alert"
        class="error-list"
      >
        <li v-for="(err, i) in errors.password" :key="i">{{ err }}</li>
      </ul>

      <button class="submit-button" type="submit" :disabled="isLoading">
        <span v-if="isLoading" class="spinner"></span>
        {{ isLoading ? 'Creating...' : 'Create User' }}
      </button>
    </form>
  </div>
</template>

<style scoped>
.form-wrapper {
  max-width: 500px;
  width: 80%;
  background-color: #efeef5;
  padding: 24px;
  margin: auto;
  border-radius: 8px;
}

.form {
  display: flex;
  gap: 8px;
  flex-direction: column;
}

label {
  font-weight: 700;
}

input {
  outline: none;
  padding: 8px 16px;
  height: 40px;
  font-size: 14px;
  background-color: #f8f7fa;
  border: 1px solid rgba(0, 0, 0, 0.12);
  border-radius: 4px;
}

input:disabled {
  background-color: #e0e0e0;
  cursor: not-allowed;
}

.submit-button {
  outline: none;
  border-radius: 4px;
  border: 1px solid rgba(0, 0, 0, 0.12);
  background-color: #7135d2;
  color: white;
  font-size: 16px;
  font-weight: 500;
  height: 40px;
  padding: 0 8px;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-top: 8px;
  align-self: flex-end;
  cursor: pointer;
}

button:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}

.error {
  color: red;
  font-size: 0.9rem;
}

.error-list {
  color: red;
  font-size: 0.9rem;
  margin: 0.25rem 0 0 0;
  padding-left: 1.25rem;
}

.password-wrapper {
  position: relative;
  width: 100%;
}

.password-wrapper input {
  width: 100%;
  padding-right: 4rem;
  box-sizing: border-box;
}

.toggle-button {
  position: absolute;
  right: 0.5rem;
  top: 50%;
  transform: translateY(-50%);
  border: none;
  background: transparent;
  cursor: pointer;
  font-size: 0.9rem;
  color: white;
  background-color: #b6b4b4;
  padding: 4px 8px;
  border-radius: 4px;
}

.api-error {
  color: #d8000c;
  background-color: #ffbaba7d;
  border: 2px solid #ff0000;
  padding: 12px;
  margin-bottom: 16px;
  border-radius: 4px;
  text-align: center;
  font-weight: 600;
}

.spinner {
  border: 2px solid rgba(255, 255, 255, 0.3);
  border-top: 2px solid #fff;
  border-radius: 50%;
  width: 16px;
  height: 16px;
  display: inline-block;
  vertical-align: middle;
  margin-right: 8px;
  animation: spin 0.8s linear infinite;
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
</style>
